config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :transactions
      resources :users
      root to: "users#index"
    end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # add path
  root 'user#show'

  get 'deposit' => 'user#deposit', :as => 'deposit'
  get 'withdraw' => 'user#withdraw', :as => 'withdraw'
  get 'new_user_referral' => 'user#referral', :as => 'new_user_referral'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions, foreign_key: 'user_id', dependent: :destroy
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Add confirmable module only for users
  devise :confirmable if :role == 'user'

  has_many :transactions, foreign_key: 'user_id', dependent: :destroy
  attribute :role, :string, default: 'user'
  attribute :referred_num, :integer, default: 0
  attribute :unique_id, :string, default: SecureRandom.hex(3)
  validates :balance, presence: true, numericality: { allow_decimal: true, greater_than: 0 }, if: -> { role == 'user' }
  validates :firstname, :lastname, :username, :phone_number, presence: true, if: -> { role == 'user' }
  validates :username, uniqueness: true, if: -> { role == 'user' }

  after_create :assign_referral_link, if: -> { role == 'user' }

  def assign_referral_link
    self.referral_link = generate_referral_link
    save
  end

  private

  def generate_referral_link
    Rails.application.routes.url_helpers.new_user_registration_url(ref: unique_id, host: 'https://deposit-app.onrender.com')
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    def scoped_resource
      super.where(role: 'user')
    end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user if current_user.role == 'user'
    if user_signed_in?
      if current_user.role == 'admin'
        redirect_to admin_root_path
      else
        render 'user/show'
      end
    else
      redirect_to new_user_session_path
    end
  end

  def referral
    @user = current_user if current_user.role == 'user'
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    if params[:ref].present?
      session[:referrer_unique_id] = params[:ref]
      @link = session[:referrer_unique_id]
      puts "Session referred_unique_id: #{session[:referrer_unique_id]}"
    end
    super
  end

  # POST /resource
  def create
    super do |resource|
      # New user successfully saved to the database
      if resource.persisted?
        referrer_unique_id = session[:referrer_unique_id]
        puts "Session referred_unique_id in create: #{referrer_unique_id}"
        if referrer_unique_id.present?
          referrer = User.find_by(unique_id: referrer_unique_id)
          referrer&.increment!(:balance, 200)
          referrer&.increment!(:referred_num)
        end
        # Clear the referrer unique ID from the session
        session[:referrer_unique_id] = nil
      end
    end
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/_deposit.erb
<div class="shadow-md rounded-lg w-5/6 lg:w-3/5 bg-white absolute">
		<form class="flex flex-col gap-2 p-6">
			<div class="flex flex-col gap-1">
				<label for="FullName">Full name (on the card)</label>
				<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md" required />
			</div>
			<div class="flex flex-col gap-1">
				<label for="FullName">Card number</label>
				<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md" required />
			</div>
			<div>
				<div class="flex flex-col md:flex-row gap-2">
					<div>
						<label for="FullName">Expiration</label>
						<div class="flex md:flex-row flex-col  gap-3">
							<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md" required />
							<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md" required />
						</div>
					</div>
					<div class="md:absolute md:right-6  flex flex-col md:items-center">
						<label for="FullName">CVC</label>
						<div class="flex flex-col md:flex-row gap-2">
							<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md md:w-20 w-full"
								required />
						</div>
					</div>
				</div>
			</div>
			<span class="my-2 w-full bg-blue-600 p-2 text-white hover:bg-blue-800 active:bg-blue-900 rounded-md border border-blue-600 text-center font-bold"> 
				<button type="submit">
				Deposit
			</button>
			</span>
		</form>
	</div>

app/views/user/_message.erb
<div class="bg-blue-600 text-center p-3 py-5 w-full text-white">
	Sorry! online payment method is not avaialable for now, Please contact our customer support line
	<span class="font-bold">+2348144580946</span> to complete your transaction
</div>

app/views/user/_navbar.erb
<nav class="bg-purple md:px-2 py-2 relative">
		<div class="flex flex-wrap items-center justify-between p-2">

			<p class="flex flex-col px-4 py-2 font-bold text-1xl text-center text-white">
				User Id <span><%= @user.unique_id%></span>
			</p>
				
			<ul
				class = "flex text-1xl md:text-[18px]
				px-2 gap-3  text-white justify-center items-center" 
			>
			
				<li class="w-full hover:bg-gray-600 active:bg-gray-700 md:active:bg-transparent md:hover:bg-transparent text-center duration-75 rounded-md">
					<p class="block px-4 py-2  font-bold text-1xl">
						Balance <span class="block">R <%= @user.balance%> </span>
					</p>
				</li>
				<li class="w-full hover:bg-gray-600 active:bg-gray-700 md:active:bg-transparent md:hover:bg-transparent text-center duration-75 rounded-md">
					<span class="block px-4 py-2 font-bold text-1xl">
						Referred 
            <span class="block"><%= @user.referred_num %> </span>
					</span>
				</li>
		</ul>

		<div>

			<div>
      <button class="relative group harmbugger">
        <div class="bg-[#990b99] relative flex overflow-hidden items-center justify-center rounded-full w-[50px] h-[50px] transform transition-all  ring-0 hover:bg-[#8a098a] group-focus:ring-4 ring-opacity-30 duration-200 shadow-lg active:bg-[#690869]">
          <div class="flex flex-col justify-between w-[20px] h-[20px] transform transition-all duration-300 overflow-hidden">
            <div class="bg-white h-[2px] w-7 transform transition-all  group-focus:w-2/3 delay-150"></div>
            <div class="bg-white h-[2px] w-7 rounded transform transition-all duration-300"></div>
            <div class="bg-white h-[2px] w-7 transform transition-all duration-300 group-focus:w-2/3 delay-150"></div>
          </div>
        </div>
      </button>
    </div>

			<div class="absolute right-0 z-10 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden menu duration-100" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
     <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-500 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Edit Profile", edit_user_registration_path %></span>
    </div>
		<div cl	ass="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-500 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Refer A Friend", new_user_referral_path %></span>
    </div>
    <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-500 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Deposit", deposit_path %></span>
    </div>
     <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-500 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= link_to "Withdraw", withdraw_path %></span>
    </div>
    <div class="py-1" role="none">
      <span class="text-gray-700 block px-4 py-2 text-sm hover:bg-gray-500 hover:text-white" role="menuitem" tabindex="-1", id="menu-item-2"><%= button_to "Logout", destroy_user_session_path, method: :delete %></span>
    </div>
  </div>
	</div>
</nav>

app/views/user/_table.erb
<table class="shadow-lg bg-white border-separate rounded-md p-2 w-full mt-4">
  <tr class="p-3">
    <th class="bg-blue-100 border text-left px-6 py-4">Amount</th>
    <th class="bg-blue-100 border text-left px-6 py-4">Coupon</th>
    <th class="bg-blue-100 border text-left px-6 py-4">Bonus</th>
  </tr>
  <tr>
    <td class="border px-6 py-4">Alfreds Futterkiste</td>
    <td class="border px-6 py-4">Dante Sparks</td>
    <td class="border px-6 py-4">Italy</td>
  </tr>
  <tr class="p-3">
    <td class="border px-6 py-4">Centro comercial Moctezuma</td>
    <td class="border px-6 py-4">Neal Garrison</td>
    <td class="border px-6 py-4">Spain</td>
  </tr>
  <tr>
    <td class="border px-6 py-4">Ernst Handel</td>
    <td class="border px-6 py-4">Maggie O'Neill</td>
    <td class="border px-6 py-4">Austria</td>
  </tr>
  <tr class="p-3">
    <td class="border px-6 py-4">Centro comercial Moctezuma</td>
    <td class="border px-6 py-4">Neal Garrison</td>
    <td class="border px-6 py-4">Spain</td>
  </tr>
</table>

app/views/user/deposit.html.erb
<%= render "message" %>
<div class="bg-gray-100 h-screen w-90 flex justify-center items-center relative">
	<%= render "deposit" %>
</div>

app/views/user/referral.html.erb
<div class="h-screen w-screen flex flex-col justify-center bg-referral p-4"
	style="background-image:
	url('https://fiverr-res.cloudinary.com/q_auto/general_assets/referral_program/assets/f1/banner_background_md.jpg'); background-size: cover; background-position: center;"
>
	<div>
		<div class="py-10  w-full flex flex-col items-center  gap-5">
			<h3 class="font-bold text-5xl text-center text-white">
				Invite Friends & <br /> You Get Up To R200
			</h3>
			<p class="text-2xl font-medium text-gray-300 text-center">
				Introduce your friends to the easiest way to get things done
			</p>
			<form class="w-full md:w-4/5 bg-white p-6 md:rounded-md flex flex-col gap-8 shadow-lg">
				<div class="flex flex-col md:flex-row w-full gap-3">
					<input type="email" placeholder="Email Address"
						class="rounded-md outline-none border border-gray-200 p-2 flex-1 " />
						<span
							class="rounded-md flex text-white font-bold bg-blue-600 hover:opacity-90 active:bg-blue-900 w-full md:w-24
							justify-center items-center p-3">
							<button type="submit">
								Send
							</button>
						</span>
				</div>
				<hr />
				<div class="flex flex-col md:flex-row justify-center items-center gap-3">
					<div class="border border-gray-200 rounded-md w-full flex space-between">
						<input class="flex-1 p-2 outline-none referral-link" readOnly value="<%= @user.referral_link %>" />
						<span class="p-3 bg-gray-200  border border-gray-200 hover:bg-gray-300 hover:border-gray-300 active:bg-gray-400 active:border-gray-400 copy-button">
							<button type="button" onclick="handleCopyClick()">
								Copy Link
							</button>
						</span>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

app/views/user/show.html.erb
<% resource_name = :user %>
<%= render 'navbar' %>
<section
		class="bg-gray-100 border border-top:gray-200 md:border-none md:p-10 w-full flex flex-col md:flex-row gap-2">
		<div class="flex flex-col gap-3 w-full md:w-1/4">
			<div class="bg-white rounded-sm p-4 flex flex-col gap-3 w-full">
				<div class="flex items-center gap-4 justify-center">
					
					<p class="font-bold text-2xl text-gray-700 line-clamp-3 text-center">
						<%= @user.firstname %> <%= @user.lastname %> 
					</p>
				</div>
				<span class="border border-gray-200 rounded-md p-5"><%= @user.firstname %></span>
				<span class="border border-gray-200 rounded-md p-5">
					<%= @user.lastname %>
				</span>
				<span class="border border-gray-200 rounded-md p-5 line-clamp-3">
					<%= @user.email %>
				</span>
				<span class="border border-gray-200 rounded-md p-5">
					<%= @user.phone_number %>
				</span>
			</div>
			<div class="bg-white rounded-sm p-6 flex flex-col gap-5 w-full text-center">
				<span class="text-white bg-green-700 rounded-lg p-2 flex items-center justify-center gap-4 hover:bg-green-800
					active:bg-green-900">
					<a href="https://wa.me/2347017300783?text=How%20can%20we%20help%20you%20please">
						Chat with us
					</a>
				</span>

				<h2 class= "font-bold text-center mb-3">Delete account</h2>
				<p>
					<span>
						ATTENTION! All of your data will be definitely and irreversibly
						deleted
					</span>
					<br />
					Please click button below
				</p>
				
				<span class="text-white bg-red-700 rounded-lg p-2 flex items-center justify-center gap-4 hover:bg-red-800
					active:bg-red">
					<button>
						<%= button_to "Delete my account", registration_path(resource_name), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete%>
					</button>
				</span>
			</div>
		</div>
		<div class="w-full md:flex-1 flex flex-col gap-3">
			<div class="bg-white border border-gray-200 rounded-sm w-full p-8 text-gray-600 flex flex-col gap-3">
				<h2 class="font-bold text-2xl text-center">
					3 steps to to cash out more
				</h2>
				<div class="flex flex-col md:flex-row w-full md:items-baseline justify-between gap-7 mt-7">
					<div class="flex flex-col items-center justify-center gap-3">
						<p class="text-center">
							Get R200 when people register with your referral link
						</p>
					</div>
					<div class="flex  flex-col justify-center items-center gap-3">
						<p class="text-center">
							Buy coupon code to get 3x of deposit amount
						</p>
					</div>
					<div class="flex flex-col items-center justify-center gap-3">
						<p class="text-center">
							Login daily to get R200 in your balance
						</p>
					</div>
				</div>
			</div>
			<div class="mt-6">
				<h2 class="font-bold text-2xl text-center mb-4">Coupon code sales breakdown</h2>
				<p class="text-center">Note: NFX bonus purchased will automatic add to your balance</p>
				<%= render "table" %>
			</div>
		</div>
</section>
<%= render 'shared/footer' %>

app/views/user/withdraw.html.erb
<%= render "message" %>
<div class="bg-gray-100 h-screen w-90 justify-center items-center flex p-10 md:p-0 relative">
	<div class="shadow-md rounded-lg absolute bg-white w-5/6 lg:w-3/5">
		<form class="flex flex-col gap-2 p-6">
			<div>
				<div class="flex flex-col gap-1">
					<label htmlFor="email">Email</label>
					<input type="email" name="email" id="email" class="p-2 border-gray-200 rounded-md" required />
				</div>
				<div class="flex flex-col gap-1">
					<label htmlFor="phoneNumber">Phone Number</label>
					<input type="tel" name="number" id="phoneNumber" class="p-2 border-gray-200 rounded-md" required />
				</div>
			</div>
			<hr />
			<div class="flex flex-col gap-1">
				<label for="FullName">Full name (on the card)</label>
				<input type="text" name="fullname" id="FullName" class="p-2 border-gray-200 rounded-md" required />
			</div>
			<div class="flex flex-col gap-1">
				<label for="cardNumber">Card number</label>
				<input type="text" name="cardNumber" id="cardNumber" class="p-2 border-gray-200 rounded-md" required
					max-length={16} />
			</div>
			<div>
				<div class="flex flex-col md:flex-row gap-2">
					<div>
						<label for="FullName">Expiration</label>
						<div class="flex md:flex-row flex-col  gap-3">
							<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md" required
								placeholder="MM" max-length={2} />
							<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md" required
								placeholder="YY" max-length={2} />
						</div>
					</div>
					<div class="md:absolute md:right-6  flex flex-col md:items-center">
						<label for="FullName">CVC</label>
						<div class="flex flex-col md:flex-row gap-2">
							<input type="text" name="" id="FullName" class="p-2 border-gray-200 rounded-md md:w-20 w-full"
								required max-length={3} />
						</div>
					</div>
				</div>
			</div>
			<span
				class="my-2 w-full bg-blue-600 p-2 text-white hover:bg-blue-800 active:bg-blue-900 rounded-md border border-blue-600 text-center font-bold">
				<button type="submit">
					Withdraw $20.00
				</button>
			</span>
		</form>
	</div>
</div>